language: node_js
node_js: '11'
sudo: enabled
dist: trusty
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libc6-dev-i386
      - gcc-4.8-multilib
      - g++-4.8-multilib
      - ninja-build
      - linux-libc-dev:i386
      - linux-libc-dev
      - icnsutils
      - graphicsmagick

script:
  - npm run setup
  - npm run lint
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then npm run compile-darwin ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then npm run compile-linux ;fi
